language: python

python:
  - 2.7
  - 3.4
env:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.8,<1.9'

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  ./runtests.sh


matrix:
  exclude:
    - python: 3.4
      env: DJANGO='django>=1.4,<1.5'
