language: python

python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_INSTALL="django>=1.4,<1.5"
  - DJANGO_INSTALL="django>=1.5,<1.6"
  - DJANGO_INSTALL="django>=1.6,<1.7"
  - DJANGO_INSTALL="django>=1.7,<1.8"
  - DJANGO_INSTALL="django>=1.8,<1.9"

install:
  - pip install -q $DJANGO_INSTALL
  - python setup.py -q install

script:  ./runtests.sh

matrix:
  exclude:
    - python: 3.4
      env: DJANGO_INSTALL='django>=1.4,<1.5'
    - python: 3.4
      env: DJANGO_INSTALL='django>=1.5,<1.6'
